name: Review Dog

on:
  pull_request_target:
    paths:
      - '**.{js,mjs,cjs,jsx,ts,mts,cts,tsx,vue}'
      - 'package.json'
      - 'pnpm-lock.json'
      - '.github/workflows/reviewdog.yml'

jobs:
  review-dog:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    name: Review Dog
    runs-on: ubuntu-latest
    steps:
      - name: Code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install Reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run eslint & reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm exec eslint -f rdjson . | reviewdog -f=rdjson -reporter=github-pr-review -filter-mode=nofilter -fail-on-error
