on:
  push:
    paths:
      - '**.go'
      - 'go.mod'
      - '.github/workflows/test_and_lint.yml'
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - '.github/workflows/test_and_lint.yml'

name: Test & Lint

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - run: go get
      - run: go generate ./...

      - run: go test -v -race ./...
      - run: go vet ./...

      - name: GolangCI-Lint
        uses: golangci/golangci-lint-action@v6
        if: github.event.name == 'pull_request'
        with:
          version: 'v1.60'
          args: '--timeout 9999s'
          only-new-issues: true
          skip-cache: true

      - name: GolangCI-Lint
        uses: golangci/golangci-lint-action@v6
        if: github.event.name != 'pull_request'
        with:
          version: 'v1.60'
          args: '--timeout 9999s'
          skip-cache: true
